
name: vmememe

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  main:
    name: main
    runs-on: ubuntu-latest

    steps:
      - name: checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: get rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy

      - name: build documentation
        run: cargo doc

      - name: publish documentation
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: doc
